algoritmo "MostrarNome"

var
// texto - caractere - string
// verdadeiro/falso - logco - boleam
// numero inteiro - inteiro - int
// numero decimal - real - float
nomeUsuario: caractere 

inicio
// output - saida - telas, leds, resposta por voz, som
// l - line break - quebra de linha

// nomeUsuario <- "Filipe"
escreva ("Digite seu nome")
leia(nomeUsuario)
escreva ("Oi, ")
escreval ("Bom dia" + nomeUsuario)


fimalgoritmo
